return {
    ["Name"] = "__rhello__",
    ["Version"] = "1.0.0",
    ["Description"] = "A simple example of a package.",
    ["Main"] = "out/index.luau",
    ["Author"] = "Blockguard Software Foundation (https://github.com/blockguard-sf)",
    ["License"] = "MIT License",
    ["Repository"] = "https://github.com/blockguard-sf/RoLib/tree/release/v1.0/examples/__rhello__",
    ["Dependencies"] = {},
    ["Files"] = {
        "out",
        "out.ham"
    }
}
